nelmio_api_doc:
    documentation:
        info:
            title: JobPlanner API
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc)(?!/register)
    models:
        use_jms: false
