<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260216100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'JobPlanner: refactor schema - users, job_offers, applications, etc.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS jobs');
        $this->addSql('DROP TABLE IF EXISTS addresses');
        $this->addSql('DROP TABLE IF EXISTS countries');

        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');

        $this->addSql('CREATE TABLE job_offers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, url VARCHAR(2048) NOT NULL, location VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, source_url VARCHAR(2048) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_OFFER_OWNER ON job_offers (owner_id)');
        $this->addSql('ALTER TABLE job_offers ADD CONSTRAINT FK_OFFER_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE applications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_offer_id INT NOT NULL, owner_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, pipeline_position INT DEFAULT 0 NOT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_APP_JOB ON applications (job_offer_id)');
        $this->addSql('CREATE INDEX IDX_APP_OWNER ON applications (owner_id)');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_APP_JOB FOREIGN KEY (job_offer_id) REFERENCES job_offers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_APP_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE application_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, action_type VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_HISTORY_APP ON application_history (application_id)');
        $this->addSql('ALTER TABLE application_history ADD CONSTRAINT FK_HISTORY_APP FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE recruiter_emails (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, sender VARCHAR(255) NOT NULL, subject VARCHAR(1024) NOT NULL, body TEXT NOT NULL, message_id VARCHAR(64) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ai_summary TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EMAIL_MSG ON recruiter_emails (message_id)');
        $this->addSql('CREATE INDEX IDX_EMAIL_APP ON recruiter_emails (application_id)');
        $this->addSql('ALTER TABLE recruiter_emails ADD CONSTRAINT FK_EMAIL_APP FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE follow_up_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT DEFAULT NULL, days_without_reply INT NOT NULL, template_type VARCHAR(50) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RULE_OWNER ON follow_up_rules (owner_id)');
        $this->addSql('ALTER TABLE follow_up_rules ADD CONSTRAINT FK_RULE_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE scheduled_follow_ups (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, generated_content TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_SCHED_APP ON scheduled_follow_ups (application_id)');
        $this->addSql('ALTER TABLE scheduled_follow_ups ADD CONSTRAINT FK_SCHED_APP FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE interviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(50) NOT NULL, notes TEXT DEFAULT NULL, location_or_link VARCHAR(512) DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, reminder_sent BOOLEAN DEFAULT false NOT NULL, reminder_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_INT_APP ON interviews (application_id)');
        $this->addSql('ALTER TABLE interviews ADD CONSTRAINT FK_INT_APP FOREIGN KEY (application_id) REFERENCES applications (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE ai_generation_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, type VARCHAR(50) NOT NULL, prompt TEXT DEFAULT NULL, tokens_used INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AI_USER ON ai_generation_logs (user_id)');
        $this->addSql('ALTER TABLE ai_generation_logs ADD CONSTRAINT FK_AI_USER FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ai_generation_logs');
        $this->addSql('DROP TABLE interviews');
        $this->addSql('DROP TABLE scheduled_follow_ups');
        $this->addSql('DROP TABLE follow_up_rules');
        $this->addSql('DROP TABLE recruiter_emails');
        $this->addSql('DROP TABLE application_history');
        $this->addSql('DROP TABLE applications');
        $this->addSql('DROP TABLE job_offers');
        $this->addSql('DROP TABLE users');

        $this->addSql('CREATE TABLE countries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE addresses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_id INT NOT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, zip_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6FCA7516F92F3E70 ON addresses (country_id)');
        $this->addSql('ALTER TABLE addresses ADD CONSTRAINT FK_6FCA7516F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE jobs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reference_mail VARCHAR(255) NOT NULL, reference_phone VARCHAR(255) NOT NULL, reference_address_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A8936DC5A1A99A3A ON jobs (reference_address_id)');
        $this->addSql('ALTER TABLE jobs ADD CONSTRAINT FK_A8936DC5A1A99A3A FOREIGN KEY (reference_address_id) REFERENCES addresses (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
