<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210152730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE addresses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, zip_code VARCHAR(255) NOT NULL, country_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FCA7516F92F3E70 ON addresses (country_id)');
        $this->addSql('CREATE TABLE countries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE addresses ADD CONSTRAINT FK_6FCA7516F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE jobs ADD reference_mail VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE jobs ADD reference_phone VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE jobs ADD reference_address_id INT NOT NULL');
        $this->addSql('ALTER TABLE jobs ADD CONSTRAINT FK_A8936DC5A1A99A3A FOREIGN KEY (reference_address_id) REFERENCES addresses (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A8936DC5A1A99A3A ON jobs (reference_address_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE addresses DROP CONSTRAINT FK_6FCA7516F92F3E70');
        $this->addSql('DROP TABLE addresses');
        $this->addSql('DROP TABLE countries');
        $this->addSql('ALTER TABLE jobs DROP CONSTRAINT FK_A8936DC5A1A99A3A');
        $this->addSql('DROP INDEX IDX_A8936DC5A1A99A3A');
        $this->addSql('ALTER TABLE jobs DROP reference_mail');
        $this->addSql('ALTER TABLE jobs DROP reference_phone');
        $this->addSql('ALTER TABLE jobs DROP reference_address_id');
    }
}
